general {
    col.active_border = rgba({{colors.primary.default.hex_stripped}}ee) rgba({{colors.tertiary.default.hex_stripped}}ee) 45deg
    col.inactive_border = rgba({{colors.outline.default.hex_stripped}}aa)
}

group {
    col.border_active = rgba({{colors.on_primary_container.default.hex_stripped}}ee) rgba({{colors.tertiary.default.hex_stripped}}ee) 45deg
    col.border_inactive = rgba({{colors.outline.default.hex_stripped}}aa)
    groupbar {
        col.active = rgba({{colors.tertiary.default.hex_stripped}}ee) rgba({{colors.on_primary_container.default.hex_stripped}}ee) 45deg
        col.inactive = rgba({{colors.outline.default.hex_stripped}}ee)
    }
}

misc {
    background_color = rgb({{colors.surface_container.default.hex_stripped}})
}

plugin {
    hyprtrails {
        color = rgba({{colors.primary.default.hex_stripped}}ff)
    }
}
