{
  imports = [
    ./common.nix
    ./gpu.nix
    ./ai.nix
    ./greet.nix
    ./hyprland.nix
    ./kernel.nix
    ./openrgb.nix
    ./plex.nix
    ./power.nix
    ./rust.nix
    ./sound.nix
    ./ssh.nix
    ./steam.nix
    ./tailscale.nix
    ./udev.nix
    ./wifi.nix
    ./wine.nix
    ./xdg.nix
    ./virtualization/docker.nix
    ./virtualization/general.nix
    ./virtualization/virtualbox.nix
  ];
}
